config/routes.rb
Odot::Application.routes.draw do
  
  get "/login" => "user_sessions#new", as: :login
  delete "/user_sessions/:id" => "user_sessions#destroy", as: :destroy_user_session_path

  resources :users  
  resources :user_sessions
  resources :password_resets, only: [:new, :create, :edit, :update]

  get "todo_items/index"
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end   
  end 
  root 'todo_lists#home'

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
	has_many :todo_items
	belongs_to :user
	
	validates :title, presence: true
	validates :title, length: { minimum: 3 }
	validates :description, presence: true
	validates :description, length: { minimum: 5 }


	def has_completed_items?
		todo_items.complete.size > 0
	end	

	def has_incompleted_items?
		todo_items.incomplete.size > 0
	end	

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :require_user
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  
  def home
  end   

  def index
    @todo_lists = current_user.todo_lists
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = current_user.todo_lists.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = current_user.todo_lists.new(todo_list_params)
    @todo_list.latitude = params[:latitude]
    @todo_list.longitude = params[:longitude]

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todo_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    @todo_list.latitude = params[:latitude]
    @todo_list.longitude = params[:longitude]
    
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = current_user.todo_lists.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<html>
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  
<div class="actions">
    <%= hidden_field_tag :latitude %>
    <%= hidden_field_tag :longitude %>
  <hr>
      <div class="field">
          <h2>Add a location for this list</h2>   
            <form class="form-search">
              <div>
                <input type="text" id="searchbox" class="input-medium search-query" placeholder="Enter a location here">
              </div>
              <div class="searchLocation">
                <button id="#searchLocationBtn" class="btn btn-primary">Search for a location</button>
                <button id="#currentLocationBtn" class="btn btn-success">Add my current location</button>
            </div>
            <div align="center" id="map" style="width:400px; height:300px; margin-top: 10px;">
            </div>
            </form>
      </div>         
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script> 
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.min.js"></script>    

    <script type="text/javascript">
    $(document).ready(function(){

      var mapOptions = {
           zoom: 16,
           mapTypeId: google.maps.MapTypeId.ROADMAP,
           center: new google.maps.LatLng(-33.8679519,151.2100445)
         };

      var map = new google.maps.Map(document.getElementById("map"),mapOptions);

      var geocoder = new google.maps.Geocoder();  

         $(function() {
             $("#searchbox").autocomplete({
             
               source: function(request, response) {

              if (geocoder == null){
               geocoder = new google.maps.Geocoder();
              }
                 geocoder.geocode( {'address': request.term }, function(results, status) {
                   if (status == google.maps.GeocoderStatus.OK) {

                      var searchLoc = results[0].geometry.location;
                      var lat = results[0].geometry.location.lat();
                      var lng = results[0].geometry.location.lng();
                      var latlng = new google.maps.LatLng(lat, lng);
                      var bounds = results[0].geometry.bounds;
                            $('#latitude').val(lat);
                            $('#longitude').val(lng);

                      geocoder.geocode({'latLng': latlng}, function(results1, status1) {
                          if (status1 == google.maps.GeocoderStatus.OK) {
                            if (results1[1]) {
                             response($.map(results1, function(loc) {
                            return {
                                label  : loc.formatted_address,
                                value  : loc.formatted_address,
                                bounds   : loc.geometry.bounds
                              }
                            }));
                            }
                          }
                        });
                }
                  });
               },
               select: function(event,ui){
          var pos = ui.item.position;
          var lct = ui.item.locType;
          var bounds = ui.item.bounds;
          if (bounds){
           map.fitBounds(bounds);
          }
               }
             });
         });   
     });
    </script>
  <hr>
      <%= f.submit :value => "Create Todo List", :class => 'btn btn-primary' %> 
</div
<% end %>
</html>

app/views/todo_lists/edit.html.erb
<div id="container-list-edit">
	<h1>Edit todo List </h1>

	<%= render 'form' %>

	<button class="btn btn-info", text><%= link_to 'Show', @todo_list %></button>
	<button class="btn btn-inverse", text><%= link_to 'Back', todo_lists_path %></button>
</div>

app/views/todo_lists/home.html.erb
<div class="container">	

	<div class="airtribuo"></div> 
	<h1>Geolocate Your ToDo's . Everywhere </h1>	


	<div class="marker1 marker"></div>​
	<div class="marker2 marker"></div>​
	<div class="marker3 marker"></div>​
	<div class="marker4 marker"></div>​
	<div class="marker5 marker"></div>​
	<div class="marker6 marker"></div>​
	<div class="marker7 marker"></div>​
	<div class="marker8 marker"></div>​
	<div class="marker9 marker"></div>​
	<div class="marker10 marker"></div>​
	<div class="marker11 marker"></div>​
	<div class="marker12 marker"></div>​
	<div class="marker13 marker"></div>​
	<div class="marker14 marker"></div>​
	<div class="marker15 marker"></div>​
	<div class="marker16 marker"></div>​
	<div class="marker17 marker"></div>​
	<div class="marker18 marker"></div>​
	<div class="marker19 marker"></div>​
	<div class="marker20 marker"></div>​
	<div class="marker21 marker"></div>​
	<div class="marker22 marker"></div>​
	<div class="marker23 marker"></div>​
	<div class="marker24 marker"></div>​

</div>	

app/views/todo_lists/index.html.erb
<!DOCTYPE html>
<html>
<head>
   <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false&center&zoom=18size=300x300&markers=color:blue|label:S|">
   </script> 
</head>
<body>
  <script>
    <% if @current_user %>
      // Thanks Erik!
      window.todoListLocations = <%== ActiveSupport::JSON.encode @current_user.todo_lists %>;
    <% end %>
  </script>

<div id="container-mytodo">
    <div>
    	<h1><%= @current_user.first_name %>'s Todo Lists</h1>
  	     <button class="btn btn-warning", text><%= link_to 'New Todo list', new_todo_list_path %></button>  	
    </div>
  	<hr>  
    	<% @todo_lists.each do |todo_list| %>
    		<div id="<%= dom_id(todo_list) %>">
    			<ul class="thumbnails">
    		  	<li class="span4">
    		      <img data-src="holder.js/300x300" class="list-map"src="http://maps.google.com/maps/api/staticmap?sensor=false&center=<%= todo_list.latitude %>,<%= todo_list.longitude %>&zoom=14&size=400x400&markers=color:blue|label:S|<%= todo_list.latitude %>,<%= todo_list.longitude %>">
                <h3><%= todo_list.title %></h3>
    		      		<p><%= todo_list.description %></p>
    			      		<button class="btn btn-success", text><%= link_to "List Items", todo_list_todo_items_path(todo_list) %>
                    </button>
    			      		<button class="btn btn-info", text><%= link_to 'Show', todo_list %></button>
    			      		<button class="btn btn-warning", text><%= link_to 'Edit', edit_todo_list_path(todo_list) %></button>
    			      		<button class="btn btn-danger", text><%= link_to 'Delete', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </button>
			      </li> 
    			   <ul>	
			        <li>Latitude : <%= todo_list.latitude %></li>
			        <li>Longitude : <%= todo_list.longitude %></li>
			        <% if todo_list.longitude && todo_list.latitude %>
    				 </ul>        
    			</ul>	
    	        <% end %>
    		</div>      
    		<hr>
    	<% end %>
        <div class="dynamicPos">
          <h2>My tasks</h2>   
              <button id="watchPositionBtn", class="btn btn-success" >Watch Current Position</button>
              <button id="stopWatchBtn", class="btn btn-danger" >Stop Watch Position</button>
            <div class="alert alert-success", id="APIReturnValues"></div>
            <div id="map-canvas" style=" padding:1px; border:1px solid; height:200px; width:300px;"></div>
        </div>  
	</body> 
	<hr>  
<html>

<script>
//dynamic map setup
//Thank you Mathlida for helping troubleshoot and modify this script for 1.5 hours.
jQuery(window).ready(function(){
            jQuery("#watchPositionBtn").click(initiate_watchlocation);
            jQuery("#stopWatchBtn").click(stop_watchlocation);
        });


function initialize(latitude, longitude, ignore_bounds) {   //Thanks Joel for adding ignore_bounds here
    var mapOptions = {
        zoom: 13,
        center: new google.maps.LatLng(latitude, longitude),

        mapTypeControl: true,
        navigationControl: true,
    }
    //console.log('init', mapOptions);
    map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
    set_markers(new google.maps.LatLngBounds(null), map, ignore_bounds); //and adding ignore_bounds here
}

// Set all the markers in the location arrays and bound/frame the map
//and adding ignore_bounds here
function set_markers(bounds, map, ignore_bounds) {
    
    for (var i = 0; i < window.todoListLocations.length; i++) {
        marker = new google.maps.Marker({
            position: new google.maps.LatLng(window.todoListLocations[i].latitude, window.todoListLocations[i].longitude),
            map: map
        });
        bounds.extend(marker.position);
        google.maps.event.addListener(marker, 'click', (function (marker, i) {
            return function () {
                infowindow.setContent(locations[i][0]);
                infowindow.open(map, marker);
            }
        })(marker, i));
    }
    if (! ignore_bounds) {   //and adding ignore_bounds here
      map.fitBounds(bounds);
    }
}

 var watchProcess = null;
      
        function initiate_watchlocation() {
          if (watchProcess == null) {
              watchProcess = navigator.geolocation.watchPosition(handle_geolocation_query, handle_errors);
          }
        }
 
        function stop_watchlocation() {
          if (watchProcess != null)
          {
              navigator.geolocation.clearWatch(watchProcess);
              watchProcess = null;
          }
        }
 
        function handle_errors(error)
        {
            switch(error.code)
            {
                case error.PERMISSION_DENIED: alert("user did not share geolocation data");
                break;
 
                case error.POSITION_UNAVAILABLE: alert("could not detect current position");
                break;
 
                case error.TIMEOUT: alert("retrieving position timedout");
                break;
 
                default: alert("unknown error");
                break;
            }
        }
 
        function handle_geolocation_query(position) {
          console.log(position.coords.latitude);
          console.log(position.coords.longitude);
          var text = "Current latitude: "  + position.coords.latitude  + "<br/>" +
                     "Current longitude: " + position.coords.longitude + "<br/>" +
                     //"position.coords.altitude: " + position.coords.altitude + "<br/>" +
                     //"position.coords.accuracy(meters): "  + position.coords.accuracy  + "<br/>" +
                     //"position.coords.altitudeAccuracy(meters): "  + position.coords.altitudeAccuracy  + "<br/>" +
                     //"position.coords.heading: "  + position.coords.heading  + "<br/>" +
                     //"position.coords.speed: "  + position.coords.speed  + "<br/>" +
                     "Current timestamp: " + new Date(position.timestamp);
                     initialize(position.coords.latitude, position.coords.longitude, true)
          jQuery("#APIReturnValues").html(text);
          jQuery("#APIReturnValues").css("border","3px solid green");
 
          // var image_url = "http://maps.google.com/maps/api/staticmap?sensor=false&center=" + position.coords.latitude + ',' + position.coords.longitude +
          //                 "&zoom=18&size=300x300&markers=color:blue|label:S|" + position.coords.latitude + ',' + position.coords.longitude;
          
          // jQuery("#googleMap").html(
          //     jQuery(document.createElement("img")).attr("src", image_url)
          // );
        }

google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/todo_lists/new.html.erb
<h1>New todo List</h1>

<%= render 'form' %>

<button class="btn btn-inverse", text><%= link_to 'Back', todo_lists_path %></button>

app/views/todo_lists/show.html.erb
<div id="container-todoedit">
<h1><%= @todo_list.title %></h1>
  
<h2><%= @todo_list.description %></h2>

<% if @todo_list.has_incompleted_items? %>
<h3 id="incomplete">Incomplete Items:</h3>

<ul>
	<% @todo_list.todo_items.incomplete.each do |todo_item| %>
	<li><%= todo_item.content %></li>
	<% end %>
</ul>
<% end %>

<% if @todo_list.has_completed_items? %>
<h3 id="complete">Complete Items:</h3>

<ul>
	<% @todo_list.todo_items.complete.each do |todo_item| %>
	<li><%= todo_item.content %></li>
	<% end %>
</ul>
<% end %>

<button class="btn btn-warning", text><%= link_to 'Edit', edit_todo_list_path(@todo_list) %></button> 
<button class="btn btn-inverse", text><%= link_to 'Back', todo_lists_path %></button>

</div>