config/routes.rb
Odot::Application.routes.draw do
  
  get "/login" => "user_sessions#new", as: :login
  delete "/user_sessions/:id" => "user_sessions#destroy", as: :destroy_user_session_path

  resources :users  
  resources :user_sessions
  resources :password_resets, only: [:new, :create, :edit, :update]

  get "todo_items/index"
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end   
  end 
  root 'todo_lists#home'

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:email])
  	 if user && user.authenticate(params[:password])
	  	  session[:user_id] = user.id
	  	  flash[:success] = "Thanks for logging in #{current_user.first_name} !"
	  	  redirect_to todo_lists_path
	   else
		    flash[:error] = "Oh No..there was a problem logging in. Please check your email and password"
		    render action: 'new'
	   end	  
  end

  def destroy
  	session[:user_id] = nil
    redirect_to root_path
  end	

end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<div id="container-login">
<h1>Airtribuo</h1>
<%= form_tag user_sessions_path do %>
	<%= label_tag :email, "Email Address" %>
	<%= text_field_tag :email, params[:email] %>
	<br/>

	<%= label_tag :password, "Password" %>
	<%= password_field_tag :password %>
	<br/>
	
	<p class="login"><%= submit_tag "Log In", :class => "btn btn-primary" %></p>

	<p><button class="btn btn-inverse", text><%= link_to "Forgot Password", new_password_reset_path %></button></p>
<% end %>	
	<body="preloaded">
	      <div class="marker1 marker"></div>​ 
            <div class="marker2 marker"></div>​
            <div class="marker3 marker"></div>​
            <div class="marker4 marker"></div>​
            <div class="marker5 marker"></div>​
            <div class="marker6 marker"></div>​
            <div class="marker7 marker"></div>​
            <div class="marker8 marker"></div>​
            <div class="marker9 marker"></div>​
            <div class="marker10 marker"></div>​
            <div class="marker11 marker"></div>​
            <div class="marker12 marker"></div>​ 
            <div class="marker13 marker"></div>​
            <div class="marker14 marker"></div>​
            <div class="marker15 marker"></div>​
            <div class="marker16 marker"></div>​
            <div class="marker17 marker"></div>​
            <div class="marker18 marker"></div>​
            <div class="marker19 marker"></div>​
            <div class="marker20 marker"></div>​
            <div class="marker21 marker"></div>​
            <div class="marker22 marker"></div>​
            <div class="marker23 marker"></div>​
            <div class="marker24 marker"></div>​
          </body>  
</div>    